### ISSUE TITLE
Content Publishing - Changes Not Reflected

### ISSUE THREAD

**Issue by Mr920** [IBM-Bluemix-Docs/hardware-firewall-dedicated#22]
This is a continuation of : https://github.com/IBM-Bluemix-Docs/hardware-firewall-dedicated/pull/21

We are not seeing that the published documentation reflects the most recent merge

What is the typical timeline for a request like this?
@jbmitch

**Comment by jbmitch** [comment]
Hi @Mr920 

This content is replicated. The reason you aren't seeing it is because you're using the old URL. The URLs have changed to a new format, and the old URLs point to an archived version of the docs at the moment, until they deactivate soon. The correct and live version of the topic you're wondering about is here:

https://cloud.ibm.com/docs/infrastructure/hardware-firewall-dedicated?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges#ibm-cloud-ip-ranges

Note the URL format, and update your bookmarks as is appropriate. Again, the older URLs will cease functioning soon, and return 404s.
